name: React App Linting
on:
  push:
    paths:
      - src/**
      - __tests__/**
      - __mocks__/**
      - .eslintrc.js
      - .github/workflows/linting.yaml

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: check types
        run: npm run type-check

      - name: lint
        if: always()
        run: npm run lint
        
      - name: prettier
        if: always()
        run: npm run prettier

      - name: Upload linting coverage
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7
